### ISSUE TITLE
[DOCUMENTATION] Hull Data Creation Guide

### ISSUE THREAD

**Issue by TeaRussell** [Liam-Harrison/Celeritas#196]
TODO: Write up [the hull data creation guide](https://github.com/Liam-Harrison/Celeritas/wiki/Hull-Data-Creation-Guide) page.

@rdpolarity I'm pretty sure there was a reason, but if you could let me know in a comment here WHY you need to center the layout on the 'back of ship' axis, that'd be appreciated!  -T.

**Comment by rdpolarity** [comment]
It's centred so that aligning the hull and the ship easier otherwise it'd be in the corner and or potentially completely seperate from the hull floating somewhere in space (depending on how you design the layout), Its at the back because that's just where it starts, aligning it to centre in the other direction would be and extra effort not do I think it'd be helpful. Idk if that what you were asking for. The wall generation stuff is complex and deals with so many weird axis problems.

**Comment by TeaRussell** [comment]
Done!
