### ISSUE TITLE
[REQUEST] Check module functionality with all weapons

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#252]
The modules and their abilities must function cohesively with all weapons, allowing interesting synergies and play styles.

**Describe the solution you'd like**
Routinely check all modules and weapons to ensure functionality is present. Document findings or fix errors as they come, so solutions can be prepared later down the line or bugs can be ironed out immediately.

**Comment by LiamCMoore** [comment]
Whilst some limited issues were discovered with various modules. From what I can tell upon investigation, most of these issues would require a total rework of the weapon in question, or massive programmer investment to get working in a *slightly* more intuitive way. This issue is not worth further time investment, at least not until much later in development.

Closing.
