### ISSUE TITLE
[REQUEST] Hotkey to hide instructions

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#276]
The instructions when starting the game obscure a fair portion of the screen and do not disappear. 

There should now be an X to hide the menu, both appearing as a tab on the side with an X, and this can also be wired to X to close it from the keyboard. Once this is clicked, the menu disappears, and can be accessed from hitting escape and going to controls or settings there.

The menu should also autohide after a period of 30 seconds (can be adjusted later).

**Comment by TeaRussell** [comment]
(Forgot, done at almost the end of the task, whoops.)

Task Estimation (time): I think about 1, so 2h.
Does this issue address a risk? The risk is 'if this isn't done, it's really annoying'!

Risks: I'm actually pretty confident about this one, for once!
Risk Resolution: n/a

**Comment by TeaRussell** [comment]
Actual time taken: ~1:40! Actually less than double my initial guess, that's pretty good!

Testing procedure: (pick one) Playtest
Test Pass Condition(s):  The combat tutorial toggles off when it's supposed to (click the button, press x, time.  It also comes back if you press x when it's off! Yeah!!!

Risk: X may not be the best button for this?
Risk Resolution: Will need playtesting feedback.

Risk: Can't add the option to the pause menu, as the pause menu isn't implemented yet.
Risk Resolution: Since it's already working when toggled three different ways, I don't anticipate a fourth being difficult to add.

Risk: Button outline kinda pixelated.
Risk Resolution: This may just be my machine; will need testing on other machines/as an actual build/etc.  If needed can rexport the button image as a svg; it's just made in Figma so everyone has access to it. :)
