### ISSUE TITLE
[REQUEST] Tractor Beam Area of Effect

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#285]
For now, the tractor beam needs a larger area of effect.

**Comment by LiamCMoore** [comment]
Writing up the module info here so as to not deprecate Ebony's tasks:

Due to tractor beam modules not being direct damage. Their power and scaling can afford to be much stronger than that for damage based modules.

Module - Expansive Grasp
Basic Functionality:
Your tractor beam now effects all entities in an area around your target, rather than a single entities. Note that different entities of differing mass may be moved at varying speeds by the beam.

Stats:
Area of effect: This value will require testing, start with something around 5% of the screen-space.

Level 1: As above.
Subsequent Levels: Each level will increase the radius of the effect by 50%.

**Comment by MistaMishMash** [comment]
Task Estimation (time): 2.5 hours?
Does this issue address a risk? Same as the other issue (#286 ), players aren't using the tractor beam, so these modules are here to encourage its usage.

Risks: It's a bit tricky to balance this weapon
Risk Resolution: while working on #286 , I have exposed the tractor beam setting variables (eg power, reach, deadzone) so that designers and developers can tweak them without touching the code.

**Comment by MistaMishMash** [comment]
Actual time taken: 3 hours 20 minutes

Testing procedure: (pick one) Playtest 
Test Pass Condition(s):  First, tried tractor beaming without the module equipped to ensure it only tractor-beamed 1 asteroid
Then I equipped the module and tried tractor beaming. All asteroids within range were tractor-beamed as a result.

Risks: Same as other module, may be difficult to balance and need changes later
Risk Resolution: module's values / parameters are easy to change through the inspector
