### ISSUE TITLE
[REQUEST] Tractor beam Power

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#286]
The tractor beam requires more power as it is used to move other objects around.

**Comment by LiamCMoore** [comment]
Writing up the module info here so as to not deprecate Ebony's tasks:

Due to tractor beam modules not being direct damage. Their power and scaling can afford to be much stronger than that for damage based modules.

Module - Improved Gravity Clamps
Basic Functionality:
When grabbing enemy ships with your tractor beam, this module allows you to throw them around with far greater ease. Pulling enemies into the firing lines of their allies or into asteroids can be performed with ease.

Stats:
Intensity of effect: Tractor beam treats enemy ships mass as 60% lower for the purposes for moving them.

Level 1: As above.
Subsequent Levels: Treats the enemies mass as an additional 10% lower for each level past the first. At level 5 enemy ships can be moved as though they have 0 mass.

**Comment by MistaMishMash** [comment]
Task Estimation (time): 3
Does this issue address a risk? Kinda, currently players don't really use the tractor beam much. We are hoping to encourage them to use it more by adding in modules for it.

Risks: not really. might need to refactor a bit as the tractor beam is old code.
Risk Resolution: have allowed extra time in my time estimation.

**Comment by MistaMishMash** [comment]
Actual time taken: 2 hours 40 minutes

Testing procedure: (pick one) Playtest
Test Pass Condition(s):  Tried throwing some asteroids around. Then equipped the tractor beam power module, and made sure that the throw felt more powerful.

Risks: Module might need to be balanced further
Risk Resolution: All values are easy to change in the System Data, through odin inspector, so designers and programmers can both tweak easily.
